version: '3.8'

services:
  blog-system:
    build: .
    container_name: blog-system-web
    depends_on:
      - db
    volumes:
      - ./static/:/app/staticfiles
    env_file:
      - .env.prod

  db:
    image: postgres:17
    container_name: blog-system-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

volumes:
  postgres_data:
