version: '3.8'

services:
  blog-system:
    build: .
    container_name: blog-system-web
    depends_on:
      - db
    volumes:
      - ./static/:/app/staticfiles
    env_file:
      - .env.prod

  db:
    image: postgres:17
    container_name: blog-system-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - blog-system
volumes:
  postgres_data:
